<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <OutputType Condition="$([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('win-'))">WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Xas.Core/Xas.Core.csproj" /><ProjectReference Include="../Xas.Input/Xas.Input.csproj" /></ItemGroup>
  <ItemGroup><InternalsVisibleTo Include="Xas.Tests" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="winfsp.net" Version="2.2.26215" />
  </ItemGroup>
</Project>
